### ISSUE TITLE
Dosent work for multiple gridviews in single page

### ISSUE THREAD

**Issue by Michel5588BB** [nterms/yii2-pagesize-widget#10]
Hi,

I am trying to use this extension in a single page i.e. the tabbed views and I can see the extension isn't working for me.

**Comment by nterms** [comment]
Try this:

Use an ID for each of the instances of the widget.

``` php
<?php echo \nterms\pagesize\PageSize::widget(array(
    'options' => array(
        'id' => 'tab1-page-size',
    ),
)); ?>
```

Then use that ID as the selector for respective GridView .

``` php
<?= GridView::widget([
     'dataProvider' => $dataProvider,
     'filterModel' => $searchModel,
        'filterSelector' => '#tab1-page-size',
     'columns' => [
         ...
     ],
 ]); ?>
```

Change the ID to match your tab names.

**Comment by nterms** [comment]
@Michel5588BB Hope that above solved your problem.
