### ISSUE TITLE
Not working if pageSizeParam is array

### ISSUE THREAD

**Issue by honsa** [nterms/yii2-pagesize-widget#11]
Hello

Thank you for this nice little plugin.

It seems working fine to set the pageSize, except the actual perPage set of the dropdownList does not work if pageSizeParam is an array like 

`'pageSizeParam' => 'ModelSearch[per-page]'`

Instead of the selected pageSize the default value is used cause the name is not found in the $_GET data.

**Comment by nterms** [comment]
@honsa thanks for reporting this. However, arrays can go into multiple nested levels and supporting them could be complicated. If you already have a solution please send a pull request.

**Comment by honsa** [comment]
Thank you for your fast reply ;)

This is not a big problem, i just tried it with a recursive function and it is working for me. May its not bullet proof already but a good start and stable enough:

https://github.com/nterms/yii2-pagesize-widget/pull/12
