### ISSUE TITLE
The name space issue still exists in the 2.0.0 release

### ISSUE THREAD

**Issue by sjaakp** [nterms/yii2-pagesize-widget#5]

**Comment by nterms** [comment]
Unable to reproduce the error. Please provide more information.

**Comment by sjaakp** [comment]
I installed yii2-pagesize-widget v. 2.0.0 with composer. The file PageSize.php has:

 

                namespace nterms;

 

while the master branch has:

 

                namespace nterms\pagesize;

 

as it should be. I had to manually correct it to make it work.

 

Thanks, by the way. It’s a nice widget.

 

  _____  

Sjaak Priester

 <mailto:sjaak@sjaakpriester.nl> sjaak@sjaakpriester.nl

 

Van: Saranga Abeykoon [mailto:notifications@github.com] 
Verzonden: woensdag 10 juni 2015 6:38
Aan: nterms/yii2-pagesize-widget
CC: Sjaak Priester
Onderwerp: Re: [yii2-pagesize-widget] The name space issue still exists in the 2.0.0 release (#5)

 

Unable to reproduce the error. Please provide more information.

**Comment by nterms** [comment]
@sjaakp Thanks a lot for pointing this out. Released v2.0.1 with the issue fixed.
